# Dependencies
#highlighter:      pygments # no longer needed

# Permalinks
permalink:        pretty

# Setup
title:            Particulate Matters
tagline:          'a blog about technical minutia'
description:      'a chronicle of victories over small obstacles.'
url:              http://chrisjcameron.github.io
baseurl:          /

author:
  name:              Christopher J. Cameron
  url:               https://about.me/christophercameron
  email:             chris.j.cameron@gmail.com

paginate:         5

# Custom vars
version:          1.0

github:         https://github.com/chrisjcameron
#repo:           https://github.com/poole/hyde
